import "./globals.css";

export const metadata = {
  title: "Floor Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script async src="https://js.stripe.com/v3/pricing-table.js"></script>
      </head>
      <body>{children}</body>
    </html>
  );
}
